#!/usr/bin/env perl
use v5.38;
no feature qw(module_true);

use Mojo::File qw(curfile);
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('Moove');
