swagger: '2.0'
info:
  title: Cardio Tracker
  description: ''
  version: 1.0.0
  contact:
    email: ct@digicow.net
host: ct.digicow.net
schemes:
  - https
basePath: /api/v1
securityDefinitions:
  user:
    type: apiKey
    in: header
    name: X-API-Key
  admin:
    type: apiKey
    in: header
    name: X-API-Key
security:
  - user: []
paths:
  /legacy/events/{username}:
    get:
      summary: Get a list of a user's events
      x-mojo-to: 'API::V1::Legacy#get_events'
      parameters:
      - name: username
        in: path
        type: string
        required: true
        description: name of user
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              past_events:
                type: array
                items:
                  $ref: '#/definitions/RegisteredEvent'
              future_events:
                type: array
                items:
                  $ref: '#/definitions/RegisteredEvent'
  /exercise:
    get:
      summary: Get a set of exercises
      x-mojo-to: 'API::V1::Exercise#get'
      produces:
        - application/json
      responses:
        '200':
          description: Successful retrieval
          schema:
            $ref: '#/definitions/Exercise'
  '/exercise/:id':
    post:
      summary: Update an exercise
      x-mojo-to: 'API::V1::Exercise#update'
      produces:
        - application/json
      responses:
        '200':
          description: Successful update
        '401':
          description: Exercise not found
definitions:
  ActivityResult:
    type: object
    properties:
      distance:
        type: string
      pace:
        type: string
      time:
        type: string
  EventCountdown:
    type: object
    properties:
      days:
        type: number
      weeks:
        type: number
      months:
        type: number
    required:
      - days
      - weeks
      - months
  Exercise:
    type: object
    properties:
      id:
        type: integer
    required:
      - id
  RegisteredEvent:
    type: object
    properties:
      date:
        type: string
      name:
        type: string
      fee:
        type: number
      fr_min:
        type: number
      fr_raised:
        type: number
      registered:
        type: string
      event_type:
        type: string
      result:
        $ref: '#/definitions/ActivityResult'
      countdown:
        $ref: '#/definitions/EventCountdown'
    required:
      - date
      - name
      - event_type